//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v10.8.6+c17d4e1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Campaign Banner</summary>
	[PublishedModel("campaignBanner")]
	public partial class CampaignBanner : PublishedContentModel, IComponentBase
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		public new const string ModelTypeAlias = "campaignBanner";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<CampaignBanner, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public CampaignBanner(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Description: The description for the banner variant
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("description")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString Description => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "description");

		///<summary>
		/// Desktop Image: The image used on the right hand side of the banner in desktop.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("desktopImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops DesktopImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "desktopImage");

		///<summary>
		/// Desktop video URL: The Youtube URL for the desktop video.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("desktopVideoURL")]
		public virtual string DesktopVideoUrl => this.Value<string>(_publishedValueFallback, "desktopVideoURL");

		///<summary>
		/// Enable overlay: Enables the darker overlay on the pull quote background image.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("enableOverlay")]
		public virtual bool EnableOverlay => this.Value<bool>(_publishedValueFallback, "enableOverlay");

		///<summary>
		/// Link: The CTA used in the banner.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("link")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Web.Common.PublishedModels.ConfigurableLink> Link => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Web.Common.PublishedModels.ConfigurableLink>>(_publishedValueFallback, "link");

		///<summary>
		/// Mobile Image: The image used on the banner in mobile.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mobileImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops MobileImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "mobileImage");

		///<summary>
		/// Mobile video URL: The Youtube URL for the Mobile video.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mobileVideoURL")]
		public virtual string MobileVideoUrl => this.Value<string>(_publishedValueFallback, "mobileVideoURL");

		///<summary>
		/// Small text: The red text situated above the title.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smallText")]
		public virtual string SmallText => this.Value<string>(_publishedValueFallback, "smallText");

		///<summary>
		/// Title: The title of the banner
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("title")]
		public virtual string Title => this.Value<string>(_publishedValueFallback, "title");

		///<summary>
		/// Variant: This toggle changes the banner into its variant. Having it on will place the description in full-width and the image as a background.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("variant")]
		public virtual string Variant => this.Value<string>(_publishedValueFallback, "variant");

		///<summary>
		/// Aspect ratio: Only applies to background background images and videos (not Inline video). If no option is selected, the content is full width.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aspectRatio")]
		public virtual string AspectRatio => global::Umbraco.Cms.Web.Common.PublishedModels.ComponentBase.GetAspectRatio(this, _publishedValueFallback);

		///<summary>
		/// Background colour: Component panel background colour (if nothing is selected, the default is Light)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("backgroundColour")]
		public virtual string BackgroundColour => global::Umbraco.Cms.Web.Common.PublishedModels.ComponentBase.GetBackgroundColour(this, _publishedValueFallback);

		///<summary>
		/// Desktop Background video: The component's background video for desktop view
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("backgroundVideo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops BackgroundVideo => global::Umbraco.Cms.Web.Common.PublishedModels.ComponentBase.GetBackgroundVideo(this, _publishedValueFallback);

		///<summary>
		/// Content alignment: Align content to left or center. Default is left. This format configuration is overwritten by the wysiwyg (rich text) field in the component's content.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contentAlignment")]
		public virtual string ContentAlignment => global::Umbraco.Cms.Web.Common.PublishedModels.ComponentBase.GetContentAlignment(this, _publishedValueFallback);

		///<summary>
		/// Desktop background image: Recommend using .webp format. The recommended ratio to resolutions are as follows: 4:3 - 1080px height 16:9 - 810px height 21:9 - 617px height
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("desktopBackgroundImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops DesktopBackgroundImage => global::Umbraco.Cms.Web.Common.PublishedModels.ComponentBase.GetDesktopBackgroundImage(this, _publishedValueFallback);

		///<summary>
		/// Enable On This Page: Enable for "On this page" widget
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("enableOnThisPage")]
		public virtual bool EnableOnThisPage => global::Umbraco.Cms.Web.Common.PublishedModels.ComponentBase.GetEnableOnThisPage(this, _publishedValueFallback);

		///<summary>
		/// Font colour: Component font colour (if nothing is selected, the default is Dark)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fontColour")]
		public virtual string FontColour => global::Umbraco.Cms.Web.Common.PublishedModels.ComponentBase.GetFontColour(this, _publishedValueFallback);

		///<summary>
		/// Mobile background image: Recommend using .webp format. The recommended ratio to resolutions are as follows: 4:3 - 743px height 16:9 - 557px height 21:9 - 425px height
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mobileBackgroundImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops MobileBackgroundImage => global::Umbraco.Cms.Web.Common.PublishedModels.ComponentBase.GetMobileBackgroundImage(this, _publishedValueFallback);

		///<summary>
		/// Mobile background video: The component's background video for mobile devices
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mobileBackgroundVideo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops MobileBackgroundVideo => global::Umbraco.Cms.Web.Common.PublishedModels.ComponentBase.GetMobileBackgroundVideo(this, _publishedValueFallback);

		///<summary>
		/// On this page anchor
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("onThisPageAnchor")]
		public virtual string OnThisPageAnchor => global::Umbraco.Cms.Web.Common.PublishedModels.ComponentBase.GetOnThisPageAnchor(this, _publishedValueFallback);

		///<summary>
		/// On this page label: Label used for the "On This Page" component
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("onThisPageLabel")]
		public virtual string OnThisPageLabel => global::Umbraco.Cms.Web.Common.PublishedModels.ComponentBase.GetOnThisPageLabel(this, _publishedValueFallback);

		///<summary>
		/// Use small heading: If enabled, the heading for the component will use the h2 tag instead of h1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("useSmallHeading")]
		public virtual bool UseSmallHeading => global::Umbraco.Cms.Web.Common.PublishedModels.ComponentBase.GetUseSmallHeading(this, _publishedValueFallback);
	}
}
