//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v10.8.6+c17d4e1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "componentBase"
	/// <summary>_component base</summary>
	public partial interface IComponentBase : IPublishedContent
	{
		/// <summary>Aspect ratio</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string AspectRatio { get; }

		/// <summary>Background colour</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BackgroundColour { get; }

		/// <summary>Desktop Background video</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Models.MediaWithCrops BackgroundVideo { get; }

		/// <summary>Content alignment</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ContentAlignment { get; }

		/// <summary>Desktop background image</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Models.MediaWithCrops DesktopBackgroundImage { get; }

		/// <summary>Enable On This Page</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		bool EnableOnThisPage { get; }

		/// <summary>Font colour</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string FontColour { get; }

		/// <summary>Mobile background image</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Models.MediaWithCrops MobileBackgroundImage { get; }

		/// <summary>Mobile background video</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Models.MediaWithCrops MobileBackgroundVideo { get; }

		/// <summary>On this page anchor</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string OnThisPageAnchor { get; }

		/// <summary>On this page label</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string OnThisPageLabel { get; }

		/// <summary>Use small heading</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		bool UseSmallHeading { get; }
	}

	/// <summary>_component base</summary>
	[PublishedModel("componentBase")]
	public partial class ComponentBase : PublishedContentModel, IComponentBase
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		public new const string ModelTypeAlias = "componentBase";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<ComponentBase, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public ComponentBase(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Aspect ratio: Only applies to background background images and videos (not Inline video). If no option is selected, the content is full width.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aspectRatio")]
		public virtual string AspectRatio => GetAspectRatio(this, _publishedValueFallback);

		/// <summary>Static getter for Aspect ratio</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetAspectRatio(IComponentBase that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "aspectRatio");

		///<summary>
		/// Background colour: Component panel background colour (if nothing is selected, the default is Light)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("backgroundColour")]
		public virtual string BackgroundColour => GetBackgroundColour(this, _publishedValueFallback);

		/// <summary>Static getter for Background colour</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBackgroundColour(IComponentBase that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "backgroundColour");

		///<summary>
		/// Desktop Background video: The component's background video for desktop view
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("backgroundVideo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops BackgroundVideo => GetBackgroundVideo(this, _publishedValueFallback);

		/// <summary>Static getter for Desktop Background video</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Models.MediaWithCrops GetBackgroundVideo(IComponentBase that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(publishedValueFallback, "backgroundVideo");

		///<summary>
		/// Content alignment: Align content to left or center. Default is left. This format configuration is overwritten by the wysiwyg (rich text) field in the component's content.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contentAlignment")]
		public virtual string ContentAlignment => GetContentAlignment(this, _publishedValueFallback);

		/// <summary>Static getter for Content alignment</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetContentAlignment(IComponentBase that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "contentAlignment");

		///<summary>
		/// Desktop background image: Recommend using .webp format. The recommended ratio to resolutions are as follows: 4:3 - 1080px height 16:9 - 810px height 21:9 - 617px height
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("desktopBackgroundImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops DesktopBackgroundImage => GetDesktopBackgroundImage(this, _publishedValueFallback);

		/// <summary>Static getter for Desktop background image</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Models.MediaWithCrops GetDesktopBackgroundImage(IComponentBase that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(publishedValueFallback, "desktopBackgroundImage");

		///<summary>
		/// Enable On This Page: Enable for "On this page" widget
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("enableOnThisPage")]
		public virtual bool EnableOnThisPage => GetEnableOnThisPage(this, _publishedValueFallback);

		/// <summary>Static getter for Enable On This Page</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		public static bool GetEnableOnThisPage(IComponentBase that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "enableOnThisPage");

		///<summary>
		/// Font colour: Component font colour (if nothing is selected, the default is Dark)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fontColour")]
		public virtual string FontColour => GetFontColour(this, _publishedValueFallback);

		/// <summary>Static getter for Font colour</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetFontColour(IComponentBase that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "fontColour");

		///<summary>
		/// Mobile background image: Recommend using .webp format. The recommended ratio to resolutions are as follows: 4:3 - 743px height 16:9 - 557px height 21:9 - 425px height
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mobileBackgroundImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops MobileBackgroundImage => GetMobileBackgroundImage(this, _publishedValueFallback);

		/// <summary>Static getter for Mobile background image</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Models.MediaWithCrops GetMobileBackgroundImage(IComponentBase that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(publishedValueFallback, "mobileBackgroundImage");

		///<summary>
		/// Mobile background video: The component's background video for mobile devices
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mobileBackgroundVideo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops MobileBackgroundVideo => GetMobileBackgroundVideo(this, _publishedValueFallback);

		/// <summary>Static getter for Mobile background video</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Models.MediaWithCrops GetMobileBackgroundVideo(IComponentBase that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(publishedValueFallback, "mobileBackgroundVideo");

		///<summary>
		/// On this page anchor
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("onThisPageAnchor")]
		public virtual string OnThisPageAnchor => GetOnThisPageAnchor(this, _publishedValueFallback);

		/// <summary>Static getter for On this page anchor</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetOnThisPageAnchor(IComponentBase that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "onThisPageAnchor");

		///<summary>
		/// On this page label: Label used for the "On This Page" component
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("onThisPageLabel")]
		public virtual string OnThisPageLabel => GetOnThisPageLabel(this, _publishedValueFallback);

		/// <summary>Static getter for On this page label</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetOnThisPageLabel(IComponentBase that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "onThisPageLabel");

		///<summary>
		/// Use small heading: If enabled, the heading for the component will use the h2 tag instead of h1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("useSmallHeading")]
		public virtual bool UseSmallHeading => GetUseSmallHeading(this, _publishedValueFallback);

		/// <summary>Static getter for Use small heading</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		public static bool GetUseSmallHeading(IComponentBase that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "useSmallHeading");
	}
}
