//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v10.8.6+c17d4e1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Door Visualiser Landing Page</summary>
	[PublishedModel("doorVisualiserLandingPage")]
	public partial class DoorVisualiserLandingPage : PublishedContentModel, IDoorVisualiser, IListing, IPageBase, IScripts, ISEO
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		public new const string ModelTypeAlias = "doorVisualiserLandingPage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<DoorVisualiserLandingPage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public DoorVisualiserLandingPage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Background Image: Image that will be split on either side of the main content area.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("backgroundImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops BackgroundImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "backgroundImage");

		///<summary>
		/// Logo Image: Centered image that normally displays the bnd logo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("logoImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops LogoImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "logoImage");

		///<summary>
		/// Visualiser Cta: Cta link to subsequent visualiser pages.  It should link to a house type page.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("visualiserCta")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Web.Common.PublishedModels.ConfigurableLink> VisualiserCta => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Web.Common.PublishedModels.ConfigurableLink>>(_publishedValueFallback, "visualiserCta");

		///<summary>
		/// Visualiser Disclaimer: Disclaimer at the bottom of the center content section.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("visualiserDisclaimer")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString VisualiserDisclaimer => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "visualiserDisclaimer");

		///<summary>
		/// Visualiser Sub Title: Main content subtitle, displayed as h2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("visualiserSubTitle")]
		public virtual string VisualiserSubTitle => this.Value<string>(_publishedValueFallback, "visualiserSubTitle");

		///<summary>
		/// Visualiser Title: Main content title, displayed as h1. Configured to use highlighted period if text ends with full stop.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("visualiserTitle")]
		public virtual string VisualiserTitle => this.Value<string>(_publishedValueFallback, "visualiserTitle");

		///<summary>
		/// Is Door Visualiser: Must be toggled to true to display either either of the door visualiser page types
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("isDoorVisualiser")]
		public virtual bool IsDoorVisualiser => global::Umbraco.Cms.Web.Common.PublishedModels.DoorVisualiser.GetIsDoorVisualiser(this, _publishedValueFallback);

		///<summary>
		/// Listing created date: Date created used for resource hub. If no date is selected, this field witll automatically populate to the current date.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("listingCreatedDate")]
		public virtual global::System.DateTime ListingCreatedDate => global::Umbraco.Cms.Web.Common.PublishedModels.Listing.GetListingCreatedDate(this, _publishedValueFallback);

		///<summary>
		/// Listing description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("listingDescription")]
		public virtual string ListingDescription => global::Umbraco.Cms.Web.Common.PublishedModels.Listing.GetListingDescription(this, _publishedValueFallback);

		///<summary>
		/// Listing desktop image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("listingDesktopImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ListingDesktopImage => global::Umbraco.Cms.Web.Common.PublishedModels.Listing.GetListingDesktopImage(this, _publishedValueFallback);

		///<summary>
		/// Listing mobile image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("listingMobileImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ListingMobileImage => global::Umbraco.Cms.Web.Common.PublishedModels.Listing.GetListingMobileImage(this, _publishedValueFallback);

		///<summary>
		/// Listing subtitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("listingSubtitle")]
		public virtual string ListingSubtitle => global::Umbraco.Cms.Web.Common.PublishedModels.Listing.GetListingSubtitle(this, _publishedValueFallback);

		///<summary>
		/// Listing title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("listingTitle")]
		public virtual string ListingTitle => global::Umbraco.Cms.Web.Common.PublishedModels.Listing.GetListingTitle(this, _publishedValueFallback);

		///<summary>
		/// Content type: The content type used by the resource hub component to filter search result
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contentType")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> ContentType => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetContentType(this, _publishedValueFallback);

		///<summary>
		/// Desktop product image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("desktopProductImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops DesktopProductImage => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetDesktopProductImage(this, _publishedValueFallback);

		///<summary>
		/// Include in megamenu: Will be included in the header megamenu if toggled.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("includeInMegamenu")]
		public virtual bool IncludeInMegamenu => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetIncludeInMegamenu(this, _publishedValueFallback);

		///<summary>
		/// Is product page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("isProductPage")]
		public virtual bool IsProductPage => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetIsProductPage(this, _publishedValueFallback);

		///<summary>
		/// Is video page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("isVideoPage")]
		public virtual bool IsVideoPage => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetIsVideoPage(this, _publishedValueFallback);

		///<summary>
		/// Megamenu image: Image used for the third level pages in the megamenu.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("megamenuImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops MegamenuImage => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetMegamenuImage(this, _publishedValueFallback);

		///<summary>
		/// Megamenu view all link: View all link (only applies to the second level page).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("megamenuViewAllLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link MegamenuViewAllLink => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetMegamenuViewAllLink(this, _publishedValueFallback);

		///<summary>
		/// Mobile product image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mobileProductImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops MobileProductImage => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetMobileProductImage(this, _publishedValueFallback);

		///<summary>
		/// Product category: The categories selected from the product categories data source. Add as many as required.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("productCategory")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> ProductCategory => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetProductCategory(this, _publishedValueFallback);

		///<summary>
		/// Product filters: The filters selected from the product filters data source. Add as many as required. This value is used by the Product Filters component
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("productFilters")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> ProductFilters => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetProductFilters(this, _publishedValueFallback);

		///<summary>
		/// Product priority: Enter a value between 0 and 1 (e.g. 0.5)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("productPriority")]
		public virtual string ProductPriority => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetProductPriority(this, _publishedValueFallback);

		///<summary>
		/// Search content type: The content types used by the search component to filter search result
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchContentType")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> SearchContentType => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetSearchContentType(this, _publishedValueFallback);

		///<summary>
		/// Search topics: The topics used by the search component to filter search result
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchTopics")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> SearchTopics => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetSearchTopics(this, _publishedValueFallback);

		///<summary>
		/// Topics: The topics used by the resource hub component to filter search result
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("topic")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> Topic => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetTopic(this, _publishedValueFallback);

		///<summary>
		/// Use page heading: Use the title as a H1 heading on the page.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("usePageHeading")]
		public virtual bool UsePageHeading => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetUsePageHeading(this, _publishedValueFallback);

		///<summary>
		/// Before body closing scripts: Scripts to be added before the closing {body} tag
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("beforeBodyClosingScripts")]
		public virtual string BeforeBodyClosingScripts => global::Umbraco.Cms.Web.Common.PublishedModels.Scripts.GetBeforeBodyClosingScripts(this, _publishedValueFallback);

		///<summary>
		/// Header scripts: Scripts to be added inside the {head} tag
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerScripts")]
		public virtual string HeaderScripts => global::Umbraco.Cms.Web.Common.PublishedModels.Scripts.GetHeaderScripts(this, _publishedValueFallback);

		///<summary>
		/// Canonical Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("canonicalUrl")]
		public virtual string CanonicalUrl => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetCanonicalUrl(this, _publishedValueFallback);

		///<summary>
		/// Page description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("description")]
		public virtual string Description => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetDescription(this, _publishedValueFallback);

		///<summary>
		/// Hide from Sitemap
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("hideFromSitemap")]
		public virtual bool HideFromSitemap => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetHideFromSitemap(this, _publishedValueFallback);

		///<summary>
		/// No Follow: meta tag for robots content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("noFollow")]
		public virtual bool NoFollow => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetNoFollow(this, _publishedValueFallback);

		///<summary>
		/// No Index: Meta tag for robots content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("noIndex")]
		public virtual bool NoIndex => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetNoIndex(this, _publishedValueFallback);

		///<summary>
		/// Open graph description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("openGraphDescription")]
		public virtual string OpenGraphDescription => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetOpenGraphDescription(this, _publishedValueFallback);

		///<summary>
		/// Open graph image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("openGraphImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops OpenGraphImage => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetOpenGraphImage(this, _publishedValueFallback);

		///<summary>
		/// Open graph title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("openGraphTitle")]
		public virtual string OpenGraphTitle => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetOpenGraphTitle(this, _publishedValueFallback);

		///<summary>
		/// Open graph type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("openGraphType")]
		public virtual string OpenGraphType => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetOpenGraphType(this, _publishedValueFallback);

		///<summary>
		/// Page keywords
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageKeywords")]
		public virtual string PageKeywords => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetPageKeywords(this, _publishedValueFallback);

		///<summary>
		/// Page site name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageSiteName")]
		public virtual string PageSiteName => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetPageSiteName(this, _publishedValueFallback);

		///<summary>
		/// Search Engine Change Frequency
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchEngineChangeFrequency")]
		public virtual string SearchEngineChangeFrequency => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetSearchEngineChangeFrequency(this, _publishedValueFallback);

		///<summary>
		/// Search Engine Relative Priority
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("searchEngineRelativePriority")]
		public virtual decimal SearchEngineRelativePriority => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetSearchEngineRelativePriority(this, _publishedValueFallback);

		///<summary>
		/// Page title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("title")]
		public virtual string Title => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetTitle(this, _publishedValueFallback);

		///<summary>
		/// Url Alias: The URL Alias to this page. You can have multiple aliases using comma as a separator.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("umbracoUrlAlias")]
		public virtual string UmbracoUrlAlias => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetUmbracoUrlAlias(this, _publishedValueFallback);
	}
}
