//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v10.8.6+c17d4e1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Find a Dealer</summary>
	[PublishedModel("findADealer")]
	public partial class FindAdealer : PublishedContentModel, IComponentBase
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		public new const string ModelTypeAlias = "findADealer";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<FindAdealer, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public FindAdealer(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Book now link: The book now link applied to all links associated with the second section of the info box.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bookNowLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link BookNowLink => this.Value<global::Umbraco.Cms.Core.Models.Link>(_publishedValueFallback, "bookNowLink");

		///<summary>
		/// Dealer Filters
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("dealerFilters")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> DealerFilters => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent>>(_publishedValueFallback, "dealerFilters");

		///<summary>
		/// Description: The text underneath the title text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("description")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString Description => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "description");

		///<summary>
		/// Link: Configurable CTA for the mobile showroom
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("link")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Web.Common.PublishedModels.ConfigurableLink> Link => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Web.Common.PublishedModels.ConfigurableLink>>(_publishedValueFallback, "link");

		///<summary>
		/// Mobile Showroom Popup: The generic message to be shown when there is a mobile showroom available near the selected address
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mobileShowroomPopup")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString MobileShowroomPopup => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "mobileShowroomPopup");

		///<summary>
		/// Mobile Showroom Popup Title: Showroom popup title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mobileShowroomPopupTitle")]
		public virtual string MobileShowroomPopupTitle => this.Value<string>(_publishedValueFallback, "mobileShowroomPopupTitle");

		///<summary>
		/// Result text: The text which appears at the top of the map after the user has performed a search. Please use the token {x} which will be replace by the number of dealers found (e.g. Found {x} dealers new you)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("resultText")]
		public virtual string ResultText => this.Value<string>(_publishedValueFallback, "resultText");

		///<summary>
		/// Title: The title text of the component
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("title")]
		public virtual string Title => this.Value<string>(_publishedValueFallback, "title");

		///<summary>
		/// Aspect ratio: Only applies to background background images and videos (not Inline video). If no option is selected, the content is full width.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aspectRatio")]
		public virtual string AspectRatio => global::Umbraco.Cms.Web.Common.PublishedModels.ComponentBase.GetAspectRatio(this, _publishedValueFallback);

		///<summary>
		/// Background colour: Component panel background colour (if nothing is selected, the default is Light)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("backgroundColour")]
		public virtual string BackgroundColour => global::Umbraco.Cms.Web.Common.PublishedModels.ComponentBase.GetBackgroundColour(this, _publishedValueFallback);

		///<summary>
		/// Desktop Background video: The component's background video for desktop view
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("backgroundVideo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops BackgroundVideo => global::Umbraco.Cms.Web.Common.PublishedModels.ComponentBase.GetBackgroundVideo(this, _publishedValueFallback);

		///<summary>
		/// Content alignment: Align content to left or center. Default is left. This format configuration is overwritten by the wysiwyg (rich text) field in the component's content.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contentAlignment")]
		public virtual string ContentAlignment => global::Umbraco.Cms.Web.Common.PublishedModels.ComponentBase.GetContentAlignment(this, _publishedValueFallback);

		///<summary>
		/// Desktop background image: Recommend using .webp format. The recommended ratio to resolutions are as follows: 4:3 - 1080px height 16:9 - 810px height 21:9 - 617px height
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("desktopBackgroundImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops DesktopBackgroundImage => global::Umbraco.Cms.Web.Common.PublishedModels.ComponentBase.GetDesktopBackgroundImage(this, _publishedValueFallback);

		///<summary>
		/// Enable On This Page: Enable for "On this page" widget
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("enableOnThisPage")]
		public virtual bool EnableOnThisPage => global::Umbraco.Cms.Web.Common.PublishedModels.ComponentBase.GetEnableOnThisPage(this, _publishedValueFallback);

		///<summary>
		/// Font colour: Component font colour (if nothing is selected, the default is Dark)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fontColour")]
		public virtual string FontColour => global::Umbraco.Cms.Web.Common.PublishedModels.ComponentBase.GetFontColour(this, _publishedValueFallback);

		///<summary>
		/// Mobile background image: Recommend using .webp format. The recommended ratio to resolutions are as follows: 4:3 - 743px height 16:9 - 557px height 21:9 - 425px height
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mobileBackgroundImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops MobileBackgroundImage => global::Umbraco.Cms.Web.Common.PublishedModels.ComponentBase.GetMobileBackgroundImage(this, _publishedValueFallback);

		///<summary>
		/// Mobile background video: The component's background video for mobile devices
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mobileBackgroundVideo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops MobileBackgroundVideo => global::Umbraco.Cms.Web.Common.PublishedModels.ComponentBase.GetMobileBackgroundVideo(this, _publishedValueFallback);

		///<summary>
		/// On this page anchor
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("onThisPageAnchor")]
		public virtual string OnThisPageAnchor => global::Umbraco.Cms.Web.Common.PublishedModels.ComponentBase.GetOnThisPageAnchor(this, _publishedValueFallback);

		///<summary>
		/// On this page label: Label used for the "On This Page" component
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("onThisPageLabel")]
		public virtual string OnThisPageLabel => global::Umbraco.Cms.Web.Common.PublishedModels.ComponentBase.GetOnThisPageLabel(this, _publishedValueFallback);

		///<summary>
		/// Use small heading: If enabled, the heading for the component will use the h2 tag instead of h1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("useSmallHeading")]
		public virtual bool UseSmallHeading => global::Umbraco.Cms.Web.Common.PublishedModels.ComponentBase.GetUseSmallHeading(this, _publishedValueFallback);
	}
}
