//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v10.8.6+c17d4e1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Page</summary>
	[PublishedModel("page")]
	public partial class Page : PublishedContentModel, IListing, IPageBase, IScripts, ISEO
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		public new const string ModelTypeAlias = "page";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<Page, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public Page(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Campaign form title: The title of the form for the modal
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("campaignFormTitle")]
		public virtual string CampaignFormTitle => this.Value<string>(_publishedValueFallback, "campaignFormTitle");

		///<summary>
		/// Campaign form content: The wysiwyg content used to insert form snippets for salesforce
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("cTADesktopContent")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString CTadesktopContent => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "cTADesktopContent");

		///<summary>
		/// Disable Eyebrow banner: Disables the global eyebrow banner from the campaign page.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("disableEyebrowBanner")]
		public virtual bool DisableEyebrowBanner => this.Value<bool>(_publishedValueFallback, "disableEyebrowBanner");

		///<summary>
		/// Disable Utility and Megamenu: Disables the primary navigation and utility navigation, replacing the navigation with the campaign page variant.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("disableUtilityAndMegamenu")]
		public virtual bool DisableUtilityAndMegamenu => this.Value<bool>(_publishedValueFallback, "disableUtilityAndMegamenu");

		///<summary>
		/// Enable override: Enables the override features for the sticky mobile navigation items.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("enableOverride")]
		public virtual bool EnableOverride => this.Value<bool>(_publishedValueFallback, "enableOverride");

		///<summary>
		/// Mobile Sticky Navigation Items Override: Replaces the global navigation items for sticky mobile for campaign pages.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mobileStickyNavigationItemsOverride")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.Link> MobileStickyNavigationItemsOverride => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.Link>>(_publishedValueFallback, "mobileStickyNavigationItemsOverride");

		///<summary>
		/// Modal ID: The ID used for CTAs to target opening the modal - the value for this field will be converted to #anchorId for CTAs where the anchor ID is configurable.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("modalID")]
		public virtual string ModalID => this.Value<string>(_publishedValueFallback, "modalID");

		///<summary>
		/// Utility Navigation Items Override: For campaign pages, configure the CTA for the navigation here. Only 1 item is allowed.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("utilityNavigationItemsOverride")]
		public virtual global::Umbraco.Cms.Core.Models.Link UtilityNavigationItemsOverride => this.Value<global::Umbraco.Cms.Core.Models.Link>(_publishedValueFallback, "utilityNavigationItemsOverride");

		///<summary>
		/// Listing created date: Date created used for resource hub. If no date is selected, this field witll automatically populate to the current date.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("listingCreatedDate")]
		public virtual global::System.DateTime ListingCreatedDate => global::Umbraco.Cms.Web.Common.PublishedModels.Listing.GetListingCreatedDate(this, _publishedValueFallback);

		///<summary>
		/// Listing description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("listingDescription")]
		public virtual string ListingDescription => global::Umbraco.Cms.Web.Common.PublishedModels.Listing.GetListingDescription(this, _publishedValueFallback);

		///<summary>
		/// Listing desktop image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("listingDesktopImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ListingDesktopImage => global::Umbraco.Cms.Web.Common.PublishedModels.Listing.GetListingDesktopImage(this, _publishedValueFallback);

		///<summary>
		/// Listing mobile image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("listingMobileImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ListingMobileImage => global::Umbraco.Cms.Web.Common.PublishedModels.Listing.GetListingMobileImage(this, _publishedValueFallback);

		///<summary>
		/// Listing subtitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("listingSubtitle")]
		public virtual string ListingSubtitle => global::Umbraco.Cms.Web.Common.PublishedModels.Listing.GetListingSubtitle(this, _publishedValueFallback);

		///<summary>
		/// Listing title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("listingTitle")]
		public virtual string ListingTitle => global::Umbraco.Cms.Web.Common.PublishedModels.Listing.GetListingTitle(this, _publishedValueFallback);

		///<summary>
		/// Content type: The content type used by the resource hub component to filter search result
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contentType")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> ContentType => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetContentType(this, _publishedValueFallback);

		///<summary>
		/// Desktop product image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("desktopProductImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops DesktopProductImage => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetDesktopProductImage(this, _publishedValueFallback);

		///<summary>
		/// Include in megamenu: Will be included in the header megamenu if toggled.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("includeInMegamenu")]
		public virtual bool IncludeInMegamenu => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetIncludeInMegamenu(this, _publishedValueFallback);

		///<summary>
		/// Is product page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("isProductPage")]
		public virtual bool IsProductPage => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetIsProductPage(this, _publishedValueFallback);

		///<summary>
		/// Is video page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("isVideoPage")]
		public virtual bool IsVideoPage => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetIsVideoPage(this, _publishedValueFallback);

		///<summary>
		/// Megamenu image: Image used for the third level pages in the megamenu.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("megamenuImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops MegamenuImage => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetMegamenuImage(this, _publishedValueFallback);

		///<summary>
		/// Megamenu view all link: View all link (only applies to the second level page).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("megamenuViewAllLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link MegamenuViewAllLink => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetMegamenuViewAllLink(this, _publishedValueFallback);

		///<summary>
		/// Mobile product image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mobileProductImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops MobileProductImage => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetMobileProductImage(this, _publishedValueFallback);

		///<summary>
		/// Product category: The categories selected from the product categories data source. Add as many as required.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("productCategory")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> ProductCategory => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetProductCategory(this, _publishedValueFallback);

		///<summary>
		/// Product filters: The filters selected from the product filters data source. Add as many as required. This value is used by the Product Filters component
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("productFilters")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> ProductFilters => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetProductFilters(this, _publishedValueFallback);

		///<summary>
		/// Product priority: Enter a value between 0 and 1 (e.g. 0.5)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("productPriority")]
		public virtual string ProductPriority => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetProductPriority(this, _publishedValueFallback);

		///<summary>
		/// Search content type: The content types used by the search component to filter search result
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchContentType")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> SearchContentType => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetSearchContentType(this, _publishedValueFallback);

		///<summary>
		/// Search topics: The topics used by the search component to filter search result
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchTopics")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> SearchTopics => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetSearchTopics(this, _publishedValueFallback);

		///<summary>
		/// Topics: The topics used by the resource hub component to filter search result
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("topic")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> Topic => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetTopic(this, _publishedValueFallback);

		///<summary>
		/// Use page heading: Use the title as a H1 heading on the page.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("usePageHeading")]
		public virtual bool UsePageHeading => global::Umbraco.Cms.Web.Common.PublishedModels.PageBase.GetUsePageHeading(this, _publishedValueFallback);

		///<summary>
		/// Before body closing scripts: Scripts to be added before the closing {body} tag
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("beforeBodyClosingScripts")]
		public virtual string BeforeBodyClosingScripts => global::Umbraco.Cms.Web.Common.PublishedModels.Scripts.GetBeforeBodyClosingScripts(this, _publishedValueFallback);

		///<summary>
		/// Header scripts: Scripts to be added inside the {head} tag
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerScripts")]
		public virtual string HeaderScripts => global::Umbraco.Cms.Web.Common.PublishedModels.Scripts.GetHeaderScripts(this, _publishedValueFallback);

		///<summary>
		/// Canonical Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("canonicalUrl")]
		public virtual string CanonicalUrl => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetCanonicalUrl(this, _publishedValueFallback);

		///<summary>
		/// Page description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("description")]
		public virtual string Description => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetDescription(this, _publishedValueFallback);

		///<summary>
		/// Hide from Sitemap
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("hideFromSitemap")]
		public virtual bool HideFromSitemap => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetHideFromSitemap(this, _publishedValueFallback);

		///<summary>
		/// No Follow: meta tag for robots content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("noFollow")]
		public virtual bool NoFollow => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetNoFollow(this, _publishedValueFallback);

		///<summary>
		/// No Index: Meta tag for robots content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("noIndex")]
		public virtual bool NoIndex => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetNoIndex(this, _publishedValueFallback);

		///<summary>
		/// Open graph description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("openGraphDescription")]
		public virtual string OpenGraphDescription => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetOpenGraphDescription(this, _publishedValueFallback);

		///<summary>
		/// Open graph image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("openGraphImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops OpenGraphImage => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetOpenGraphImage(this, _publishedValueFallback);

		///<summary>
		/// Open graph title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("openGraphTitle")]
		public virtual string OpenGraphTitle => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetOpenGraphTitle(this, _publishedValueFallback);

		///<summary>
		/// Open graph type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("openGraphType")]
		public virtual string OpenGraphType => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetOpenGraphType(this, _publishedValueFallback);

		///<summary>
		/// Page keywords
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageKeywords")]
		public virtual string PageKeywords => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetPageKeywords(this, _publishedValueFallback);

		///<summary>
		/// Page site name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageSiteName")]
		public virtual string PageSiteName => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetPageSiteName(this, _publishedValueFallback);

		///<summary>
		/// Search Engine Change Frequency
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchEngineChangeFrequency")]
		public virtual string SearchEngineChangeFrequency => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetSearchEngineChangeFrequency(this, _publishedValueFallback);

		///<summary>
		/// Search Engine Relative Priority
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[ImplementPropertyType("searchEngineRelativePriority")]
		public virtual decimal SearchEngineRelativePriority => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetSearchEngineRelativePriority(this, _publishedValueFallback);

		///<summary>
		/// Page title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("title")]
		public virtual string Title => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetTitle(this, _publishedValueFallback);

		///<summary>
		/// Url Alias: The URL Alias to this page. You can have multiple aliases using comma as a separator.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.6+c17d4e1")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("umbracoUrlAlias")]
		public virtual string UmbracoUrlAlias => global::Umbraco.Cms.Web.Common.PublishedModels.SEO.GetUmbracoUrlAlias(this, _publishedValueFallback);
	}
}
