//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v10.8.7+35c51a0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Website</summary>
	[PublishedModel("website")]
	public partial class Website : PublishedContentModel, IScripts, ISiteConfiguration
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		public new const string ModelTypeAlias = "website";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<Website, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public Website(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Api Key
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("apiKey")]
		public virtual string ApiKey => this.Value<string>(_publishedValueFallback, "apiKey");

		///<summary>
		/// ApplicationId
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("applicationId")]
		public virtual string ApplicationId => this.Value<string>(_publishedValueFallback, "applicationId");

		///<summary>
		/// Enable eyebrow banner
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[ImplementPropertyType("enableEyebrowBanner")]
		public virtual bool EnableEyebrowBanner => this.Value<bool>(_publishedValueFallback, "enableEyebrowBanner");

		///<summary>
		/// Eyebrow banner link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("eyebrowBannerLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link EyebrowBannerLink => this.Value<global::Umbraco.Cms.Core.Models.Link>(_publishedValueFallback, "eyebrowBannerLink");

		///<summary>
		/// Eyebrow banner text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("eyebrowBannerText")]
		public virtual string EyebrowBannerText => this.Value<string>(_publishedValueFallback, "eyebrowBannerText");

		///<summary>
		/// Mobile search placeholder text: The search header ghost text for mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mobileSearchPlaceholderText")]
		public virtual string MobileSearchPlaceholderText => this.Value<string>(_publishedValueFallback, "mobileSearchPlaceholderText");

		///<summary>
		/// Query Suggestion Index Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("queryIndexName")]
		public virtual string QueryIndexName => this.Value<string>(_publishedValueFallback, "queryIndexName");

		///<summary>
		/// Search Account Id
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchAccountId")]
		public virtual string SearchAccountId => this.Value<string>(_publishedValueFallback, "searchAccountId");

		///<summary>
		/// Search Collection Id: The Search IO collection name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchCollectionId")]
		public virtual string SearchCollectionId => this.Value<string>(_publishedValueFallback, "searchCollectionId");

		///<summary>
		/// Search domain: Website domain associated with the ID and collection
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchDomain")]
		public virtual string SearchDomain => this.Value<string>(_publishedValueFallback, "searchDomain");

		///<summary>
		/// Search Index Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchIndexName")]
		public virtual string SearchIndexName => this.Value<string>(_publishedValueFallback, "searchIndexName");

		///<summary>
		/// Search placeholder text: The search header ghost text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchPlaceholderText")]
		public virtual string SearchPlaceholderText => this.Value<string>(_publishedValueFallback, "searchPlaceholderText");

		///<summary>
		/// Search results page: The search results page used for redirecting the header search after using a search query
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchResultsPage")]
		public virtual global::Umbraco.Cms.Core.Models.Link SearchResultsPage => this.Value<global::Umbraco.Cms.Core.Models.Link>(_publishedValueFallback, "searchResultsPage");

		///<summary>
		/// Before body closing scripts: Scripts to be added before the closing {body} tag
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("beforeBodyClosingScripts")]
		public virtual string BeforeBodyClosingScripts => global::Umbraco.Cms.Web.Common.PublishedModels.Scripts.GetBeforeBodyClosingScripts(this, _publishedValueFallback);

		///<summary>
		/// Header scripts: Scripts to be added inside the {head} tag
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerScripts")]
		public virtual string HeaderScripts => global::Umbraco.Cms.Web.Common.PublishedModels.Scripts.GetHeaderScripts(this, _publishedValueFallback);

		///<summary>
		/// App Store Link: Link to the Apple App Store
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("appStoreLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link AppStoreLink => global::Umbraco.Cms.Web.Common.PublishedModels.SiteConfiguration.GetAppStoreLink(this, _publishedValueFallback);

		///<summary>
		/// Contact info number: Contact phone number
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactInfoNumber")]
		public virtual string ContactInfoNumber => global::Umbraco.Cms.Web.Common.PublishedModels.SiteConfiguration.GetContactInfoNumber(this, _publishedValueFallback);

		///<summary>
		/// Contact info title: Title for contact information
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactInfoTitle")]
		public virtual string ContactInfoTitle => global::Umbraco.Cms.Web.Common.PublishedModels.SiteConfiguration.GetContactInfoTitle(this, _publishedValueFallback);

		///<summary>
		/// Copyright text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("copyrightText")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString CopyrightText => global::Umbraco.Cms.Web.Common.PublishedModels.SiteConfiguration.GetCopyrightText(this, _publishedValueFallback);

		///<summary>
		/// External links: External links with images (selected from the content)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("externalLinks")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> ExternalLinks => global::Umbraco.Cms.Web.Common.PublishedModels.SiteConfiguration.GetExternalLinks(this, _publishedValueFallback);

		///<summary>
		/// Footer navigation sections
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("footerNavigationSections")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> FooterNavigationSections => global::Umbraco.Cms.Web.Common.PublishedModels.SiteConfiguration.GetFooterNavigationSections(this, _publishedValueFallback);

		///<summary>
		/// Mobile Sticky Navigation Items
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mobileStickyNavigationItems")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.Link> MobileStickyNavigationItems => global::Umbraco.Cms.Web.Common.PublishedModels.SiteConfiguration.GetMobileStickyNavigationItems(this, _publishedValueFallback);

		///<summary>
		/// Play Store Link: Google Play Store link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("playStoreLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link PlayStoreLink => global::Umbraco.Cms.Web.Common.PublishedModels.SiteConfiguration.GetPlayStoreLink(this, _publishedValueFallback);

		///<summary>
		/// robots.txt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("robotstxt")]
		public virtual string Robotstxt => global::Umbraco.Cms.Web.Common.PublishedModels.SiteConfiguration.GetRobotstxt(this, _publishedValueFallback);

		///<summary>
		/// Showroom Link: URL for the showroom link in the mobile navigation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("showroomLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link ShowroomLink => global::Umbraco.Cms.Web.Common.PublishedModels.SiteConfiguration.GetShowroomLink(this, _publishedValueFallback);

		///<summary>
		/// Showroom Link Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("showroomLinkImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ShowroomLinkImage => global::Umbraco.Cms.Web.Common.PublishedModels.SiteConfiguration.GetShowroomLinkImage(this, _publishedValueFallback);

		///<summary>
		/// Site logo: The website logo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("siteLogo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops SiteLogo => global::Umbraco.Cms.Web.Common.PublishedModels.SiteConfiguration.GetSiteLogo(this, _publishedValueFallback);

		///<summary>
		/// Site name: Global site name. This property is used if a page does not have a site name associated.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("siteName")]
		public virtual string SiteName => global::Umbraco.Cms.Web.Common.PublishedModels.SiteConfiguration.GetSiteName(this, _publishedValueFallback);

		///<summary>
		/// Social links: External social links with images (selected from external links folder)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("socialLinks")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> SocialLinks => global::Umbraco.Cms.Web.Common.PublishedModels.SiteConfiguration.GetSocialLinks(this, _publishedValueFallback);

		///<summary>
		/// Utility footer links
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("utilityFooterLinks")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.Link> UtilityFooterLinks => global::Umbraco.Cms.Web.Common.PublishedModels.SiteConfiguration.GetUtilityFooterLinks(this, _publishedValueFallback);

		///<summary>
		/// Utility Navigation Items: Add the utility navigation items here
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("utilityNavigationItems")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.Link> UtilityNavigationItems => global::Umbraco.Cms.Web.Common.PublishedModels.SiteConfiguration.GetUtilityNavigationItems(this, _publishedValueFallback);

		///<summary>
		/// Weekday opening times: Weekday opening times (free text)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("weekdayOpeningTimes")]
		public virtual string WeekdayOpeningTimes => global::Umbraco.Cms.Web.Common.PublishedModels.SiteConfiguration.GetWeekdayOpeningTimes(this, _publishedValueFallback);

		///<summary>
		/// Weekend opening times
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.8.7+35c51a0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("weekendOpeningTimes")]
		public virtual string WeekendOpeningTimes => global::Umbraco.Cms.Web.Common.PublishedModels.SiteConfiguration.GetWeekendOpeningTimes(this, _publishedValueFallback);
	}
}
